export const API = {
    ServerURL : 'http://localhost:8081',
    LogoutURL : '/api/logout',
    LoginURL : '/api/login/',
    CheckLoginURL : '/api/check-login/',
    GetNodesAndDatabases : '/api/get-nodes-and-databases/',
    GetNodes : '/api/get-nodes/',
    GetGroups : '/api/get-groups/',
    AddNode  : '/api/add-node/',
    AddGroup : '/api/add-group/',
    AddUser : '/api/add-user/',
    AddDatabase : '/api/add-database/',
    GetDashboardData : '/api/get-dashboard-data/',
    CreateAlert : '/api/alert/create',
}