export const API = {
    ServerURL : 'http://localhost:8081',
    LogoutURL : '/api/logout',
    LoginURL : '/api/login/',
    CheckLoginURL : '/api/check-login/',
    GetNodesAndDatabases : '/api/database/list',
    GetNodes : '/api/node/list',
    GetGroups : '/api/group/list',
    AddNode  : '/api/node/create',
    AddGroup : '/api/group/create',
    AddUser : '/api/user/create',
    AddDatabase : '/api/database/create',
    GetDashboardData : '/api/get-dashboard-data/',
    CreateAlert : '/api/alert/create',
    GetAlerts : '/api/alert/list',
    GetAlertLogs : '/api/alert/logs',
    AcknowledgeAlert : '/api/alert/acknowledge',
}